#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'

require RAILS_ROOT + '/config/environment'

index = 0
count = Message.count()
Message.find(:all).each { |message|
  index = index + 1
  STDERR.write( "#{index}/#{count}\n" )
  message.message_id822 = Message.normalize_message_id822(message.message_id822)
  message.in_reply_to_message_id822 = Message.normalize_message_id822(message.in_reply_to_message_id822)
  message.save!
}